name: Build

# Controls when the action will run.
on:
  push:
    tags:
      - 'release-*'

  workflow_dispatch:

jobs:
  build-android:
    name: Build Android application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '2.2.3'

      - run: flutter --version
      - run: dart --version

      - name: Build APK
        run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/flutter-apk/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
